Remove import Testing from TestMetrics in Sources folder (#199)
I'm updating
[swift-cluster-membership](https://github.com/apple/swift-cluster-membership)
library and have noticed that [Static SDK action
](https://github.com/akbashev/swift-cluster-membership/actions/runs/22078171691/job/63797724278)
fails with this error:
```
[125/138] Compiling MetricsTestKit TestMetrics.swift
/swift-cluster-membership/.build/checkouts/swift-metrics/Sources/MetricsTestKit/TestMetrics.swift:31:8: error: no such module 'Testing'
 29 | import Foundation
 30 | import Metrics
 31 | import Testing
    |        `- error: no such module 'Testing'
```

Seems like it's just a leftover from `import XCTest` when file been in
Tests folder and after refactoring just changed to `import Testing`,
when in reality no import is needed at all.